import { test } from '@playwright/test';
import { login } from '../XLSX/loginbyexcel';
import { readExcel } from './excelreader';
import path from 'path';

test('Fetch data from Excel', async ({ page }) => {
    await login(page);

    console.log('Login successful');

    // interwallet

    await page.getByRole('link', { name: 'Inter Wallet Transfer' }).click(); //Interwallet select

    const excelPath = path.join(__dirname, 'exceldata.xlsx');

    const users = readExcel(excelPath, 'interwallet') as any[];

    const user = users[0];
    for (const data of users) {

    // console.log(users);

    await page.getByLabel('Entity Type *').selectOption({ label: data.EntityType });
    //console.log("Entity Name:", data.EntityName);
    await page.locator('#walletowners').click();
    await page.locator('.ng-option').filter({ hasText: data.EntityName }).click();

    // Excel wali currency select
    await page.locator('#walletTypeArrSender').click();
    //await page.locator('#walletTypeArrSender').selectOption({ value: data.FromSettlementCurrency });
    const currencyMap: Record<string, string> = {
    'United State Dollar - (USD-USA)': '100003',
    // 'Euro - (EUR)': '100004',
    'United Arab Emirates Dirham - (AED)': '100149'
        };

    await page.locator('#walletTypeArrSender').selectOption({
    value: currencyMap[data.FromSettlementCurrency.trim()]
    });
    await page.locator('#walletTypeArrReceiver').selectOption({
    value: currencyMap[data.ToSettlementCurrency.trim()]  });
    // await page.pause();
    // Amount
    console.log("Excel Amount =", data.Amount);
    await page.locator('#amount').fill(String(data.Amount));
    console.log("Excel Rate =", data.Rate);
    await page.locator('#rate').fill(String(data.Rate));
    console.log("Excel Margin =", data.MarginPercent);
    await page.locator('#margin').fill(String(data.MarginPercent));
    console.log("Excel Remarks =", data.Remarks);
    await page.locator('#comments').fill(data.Remarks);

    const interWalletResponse = page.waitForResponse(
    response =>
    response.url().includes('manualAdjustmentInterWallet') &&
    response.request().method() === 'POST');

    await page.getByRole('button', { name: 'Submit' }).click();

    const apiResponse  = await interWalletResponse;
    const body = await apiResponse .text();
    console.log("Response Body =", body);
    const response = await interWalletResponse;
    const responseBody = await response.json();
    const MakerentityId = responseBody.currencyConversion.code;
    console.log("Generated by maker Entity ID =", MakerentityId);

    // User icon/profile dropdown
    await page.locator('#userDropdown').click();
    // Logout
    await page.getByText('Logout').click();
    await page.waitForTimeout(3000);
    await page.pause();
    await page.fill('#exampleInputEmail', 'lalit.checker');
    await page.fill('#exampleInputPassword', 'Admin@123');;
    await page.getByRole('button', { name: 'Login' }).click();

    // Checker Approval menu 
    await page.getByRole('link').filter({ hasText: 'Approval' }).click();

    const checkerEntityId = await page
    .locator('tbody tr:first-child td:nth-child(2)').innerText();

    console.log("Checker Entity ID =", checkerEntityId);

    if (MakerentityId.trim() === checkerEntityId.trim()) {
        console.log("PASS - Maker and Checker Entity IDs are SAME");

        await page.locator('i.fa-box-open').first().click();

    await page.locator('i.fas.fa-eye.text-primary').first().click();

    await page.getByRole('button', { name: 'Approve' }).click();

    } 
    else {
        console.log("FAIL - Entity IDs are DIFFERENT");
        console.log("Maker  =", MakerentityId);
        console.log("Checker =", checkerEntityId);
    }
    }
});



